{% set name = "soxr" %}
{% set version = "0.5.0" %}

package:
  name: soxr-python
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/soxr-{{ version }}.tar.gz
  sha256: 6db338bbb01b73ad31534dd48e1b1eafa767714223f7d403c7633c987bdbd719

build:
  skip: true  # [py<39]
  skip: true  # [python_impl == "pypy"]
  script: {{ PYTHON }} -m pip install . -vv -C cmake.define.USE_SYSTEM_LIBSOXR=ON
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - nanobind >=2.0.0
    - scikit-build-core >=0.9.0
    - pip
    - python
    - setuptools_scm
    - soxr
  run:
    - python
    - numpy

test:
  source_files:
    - tests/
  imports:
    - soxr
  commands:
    - pip check
    - pytest ./tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/dofuuz/python-soxr
  summary: High quality, one-dimensional sample-rate conversion library
  doc_url: https://python-soxr.readthedocs.io
  dev_url: https://github.com/dofuuz/python-soxr
  license: LGPL-2.1-or-later
  license_file: COPYING.LGPL

extra:
  recipe-maintainers:
    - dofuuz
