{% set name = "soxr" %}
{% set version = "0.4.0" %}

package:
  name: soxr-python
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/soxr-{{ version }}.tar.gz
  sha256: 02385e3de07e28ddbc19ab41216075d889575895e778ce2ada950d5f46cf6a52

build:
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv --config-settings="--build-option=--use-system-libsoxr"
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython >=3.0a7
    - numpy
    - pip
    - python
    - setuptools_scm
    - soxr
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - soxr
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dofuuz/python-soxr
  summary: High quality, one-dimensional sample-rate conversion library
  doc_url: https://python-soxr.readthedocs.io
  dev_url: https://github.com/dofuuz/python-soxr
  license: LGPL-2.1-or-later
  license_file: COPYING.LGPL

extra:
  recipe-maintainers:
    - dofuuz
