{% set name = "soxr" %}
{% set version = "0.3.3" %}

package:
  name: soxr-python
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/soxr-{{ version }}.tar.gz
  sha256: af874e9f14c4c261c22ce55972a1231c085a538c2d8fec78580b331370fdb551

build:
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv --config-settings="--build-option=--use-system-libsoxr"
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools_scm
    - soxr
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - soxr
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dofuuz/python-soxr
  summary: High quality, one-dimensional sample-rate conversion library
  doc_url: https://python-soxr.readthedocs.io
  dev_url: https://github.com/dofuuz/python-soxr
  license: LGPL-2.1-or-later
  license_file: COPYING.LGPL

extra:
  recipe-maintainers:
    - dofuuz
