{% set name = "soxr" %}
{% set version = "0.5.0.post1" %}

package:
  name: soxr-python
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/soxr-{{ version }}.tar.gz
  sha256: 7092b9f3e8a416044e1fa138c8172520757179763b85dc53aa9504f4813cff73

build:
  skip: true  # [py<39]
  skip: true  # [python_impl == "pypy"]
  script: {{ PYTHON }} -m pip install . -vv --config-settings="--build-option=--use-system-libsoxr"
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython >=3.0.0
    - numpy
    - pip
    - python
    - setuptools_scm
    - soxr
  run:
    - python
    - numpy

test:
  source_files:
    - tests/
  imports:
    - soxr
  commands:
    - pip check
    - pytest ./tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/dofuuz/python-soxr
  summary: High quality, one-dimensional sample-rate conversion library
  doc_url: https://python-soxr.readthedocs.io
  dev_url: https://github.com/dofuuz/python-soxr
  license: LGPL-2.1-or-later
  license_file: COPYING.LGPL

extra:
  recipe-maintainers:
    - dofuuz
