{% set name = "soxr" %}
{% set version = "0.3.4" %}

package:
  name: soxr-python
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/soxr-{{ version }}.tar.gz
  sha256: fe68daf00e8f020977b187699903d219f9e39b9fb3d915f3f923eed8ba431449

build:
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv --config-settings="--build-option=--use-system-libsoxr"
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython >=3.0a7
    - numpy
    - pip
    - python
    - setuptools_scm
    - soxr
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - soxr
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dofuuz/python-soxr
  summary: High quality, one-dimensional sample-rate conversion library
  doc_url: https://python-soxr.readthedocs.io
  dev_url: https://github.com/dofuuz/python-soxr
  license: LGPL-2.1-or-later
  license_file: COPYING.LGPL

extra:
  recipe-maintainers:
    - dofuuz
